# Generated by Django 6.0.3 on 2026-03-20 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('ITAQUI', 'Itaqui'), ('BRAVO', 'Bravo'), ('POTY', 'Poty'), ('MONTE_CARLOS', 'Monte Carlos')], max_length=32)),
                ('nome_produto', models.CharField(max_length=120)),
                ('descricao_produto', models.TextField(blank=True, default='')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('custo_unitario_fabrica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_unitario_loja', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['marca', 'nome_produto', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=16)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('referencia_tipo', models.CharField(max_length=32)),
                ('referencia_id', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cimento.produtocimento')),
            ],
            options={
                'ordering': ['-data_movimentacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='cimento.produtocimento')),
            ],
            options={
                'ordering': ['produto__marca', 'produto__nome_produto', 'produto_id'],
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('custo_unitario_fabrica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_entrada', models.DateField()),
                ('fornecedor', models.CharField(blank=True, default='', max_length=120)),
                ('observacao', models.TextField(blank=True, default='')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cimento.produtocimento')),
            ],
            options={
                'ordering': ['-data_entrada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('data_venda', models.DateTimeField()),
                ('tipo_saida', models.CharField(choices=[('RETIRADA', 'Retirada'), ('ENTREGA', 'Entrega')], max_length=16)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_total_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lucro_total_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True, default='')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_venda', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('peso_kg_unitario', models.DecimalField(decimal_places=3, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lucro_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_venda', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_custo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_lucro', models.DecimalField(decimal_places=2, max_digits=14)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='cimento.produtocimento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cimento.venda')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
