# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


def backfill_custo_medio(apps, schema_editor):
    Estoque = apps.get_model("cimento", "Estoque")
    for e in Estoque.objects.select_related("produto").all():
        if (e.custo_medio_unitario or 0) == 0 and (e.quantidade_atual or 0) > 0:
            e.custo_medio_unitario = e.produto.custo_unitario_fabrica
            e.save(update_fields=["custo_medio_unitario"])


class Migration(migrations.Migration):

    dependencies = [
        ("cimento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoque",
            name="custo_medio_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_custo_medio, migrations.RunPython.noop),
    ]
