# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cimento", "0002_estoque_custo_medio_unitario"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradaestoque",
            name="cancelada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venda",
            name="cancelada",
            field=models.BooleanField(default=False),
        ),
    ]
