# Generated by Django 6.0.4 on 2026-04-09 00:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_multiunit_fields(apps, schema_editor):
    Produto = apps.get_model('cimento', 'Produto')
    EntradaEstoque = apps.get_model('cimento', 'EntradaEstoque')
    ItemVenda = apps.get_model('cimento', 'ItemVenda')
    ItemOrcamento = apps.get_model('cimento', 'ItemOrcamento')

    for produto in Produto.objects.all():
        produto.unidade_estoque = produto.unidade_medida
        produto.save(update_fields=['unidade_estoque'])

    for entrada in EntradaEstoque.objects.select_related('produto').all():
        entrada.unidade_entrada = entrada.produto.unidade_estoque
        entrada.quantidade_estoque = entrada.quantidade
        entrada.custo_total = (entrada.quantidade or 0) * (entrada.custo_unitario_fabrica or 0)
        entrada.save(update_fields=['unidade_entrada', 'quantidade_estoque', 'custo_total'])

    for item in ItemVenda.objects.select_related('produto').all():
        item.unidade_venda = item.produto.unidade_estoque
        item.quantidade_estoque_baixada = item.quantidade
        item.fator_conversao_estoque = 1
        item.save(update_fields=['unidade_venda', 'quantidade_estoque_baixada', 'fator_conversao_estoque'])

    for item in ItemOrcamento.objects.select_related('produto').all():
        item.unidade_venda = item.produto.unidade_estoque
        item.quantidade_estoque_referencia = item.quantidade
        item.fator_conversao_estoque = 1
        item.save(update_fields=['unidade_venda', 'quantidade_estoque_referencia', 'fator_conversao_estoque'])


class Migration(migrations.Migration):

    dependencies = [
        ('cimento', '0004_materials_orcamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaestoque',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='unidade_entrada',
            field=models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], default='UNIDADE', max_length=20),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='fator_conversao_estoque',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='quantidade_estoque_referencia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='unidade_venda',
            field=models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], default='UNIDADE', max_length=20),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='fator_conversao_estoque',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='quantidade_estoque_baixada',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='unidade_venda',
            field=models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], default='UNIDADE', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_estoque',
            field=models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], default='UNIDADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='custo_unitario_fabrica',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='custo_medio_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='lucro_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_unitario_fabrica',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], default='UNIDADE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProdutoConversaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_origem', models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], max_length=20)),
                ('unidade_destino', models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], max_length=20)),
                ('fator_multiplicador', models.DecimalField(decimal_places=6, max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes_unidade', to='cimento.produto')),
            ],
            options={
                'ordering': ['unidade_origem', 'unidade_destino', 'id'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'unidade_origem', 'unidade_destino'), name='cimento_conv_unidade_produto_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoPrecoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_venda', models.CharField(choices=[('KG', 'Kg'), ('UNIDADE', 'Unidade'), ('LATA', 'Lata'), ('MILHEIRO', 'Milheiro'), ('CARRADA', 'Carrada'), ('METRO', 'Metro'), ('METRO_QUADRADO', 'Metro quadrado'), ('METRO_CUBICO', 'Metro cubico'), ('PACOTE', 'Pacote')], max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_venda', to='cimento.produto')),
            ],
            options={
                'ordering': ['unidade_venda', 'id'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'unidade_venda'), name='cimento_preco_venda_produto_unique')],
            },
        ),
        migrations.RunPython(backfill_multiunit_fields, migrations.RunPython.noop),
    ]
