# Generated by Django 6.0.4 on 2026-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimento', '0006_orcamento_desconto_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_material',
            field=models.CharField(choices=[('CIMENTO', 'Cimento'), ('TIJOLO', 'Tijolo'), ('AREIA', 'Areia'), ('OUTRO', 'Outro')], default='OUTRO', max_length=16),
        ),
    ]
