# Generated by Django 6.0.3 on 2026-04-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimento', '0007_alter_produto_tipo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='nome_produto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='cimento.produto'),
        ),
    ]
