# Generated by Django 6.0.3 on 2026-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimento', '0008_itemorcamento_nome_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, choices=[('ITAQUI', 'Itaqui'), ('APODI', 'Apodi'), ('BRAVO', 'Bravo'), ('POTY', 'Poty'), ('MONTE_CARLOS', 'Monte Carlos')], default='', max_length=32),
        ),
    ]
