# Generated by Django 6.0.3 on 2026-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimento', '0009_alter_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='nome_responsavel',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
